### ISSUE TITLE
Issue while using global Promise

### ISSUE THREAD

**Issue by pascalduez** [valeriangalliat/es6-denodeify#1]
``` js
const fs = require('fs')
const denodeify = require('es6-denodeify')();
const readFile = denodeify(fs.readFile)

readFile('package.json', 'utf8').then(console.log)
```

```
[...]/node_modules/es6-denodeify/index.js:12
        return new Promise(function (resolve, reject) {
               ^
TypeError: undefined is not a function
    at [...]/node_modules/es6-denodeify/index.js:12:16
    at Object.<anonymous> ([...]/index.js:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

node: 0.12 (Native Promise)

I guess the argument shouldn't be called `Promise`.

**Comment by valeriangalliat** [comment]
> I guess the argument shouldn't be called `Promise`.

You're right. I'm fixing this.

**Comment by valeriangalliat** [comment]
Fixed with 0.1.2!

**Comment by pascalduez** [comment]
Faster :-)

https://github.com/pascalduez/es6-denodeify/commit/51d0b8edee4ed967fc658d4059f0fb993501c004

**Comment by valeriangalliat** [comment]
Ha, nearly the exact same commit!

In the end I think the ultimate name would've been a capital `P`, but anyway.

**Comment by pascalduez** [comment]
Naming is hard
